name: Check editorconfig
on:
  workflow_call:
    inputs:
      checker_version:
        description: Version of `editorconfig-checker`
        default: 4.0.2
        type: string


jobs:

  editorconfig-checker:
    name: Check editorconfig
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Show Node and NPM versions
        run: |
          echo node@$(node --version)
          echo npm@$(npm --version)

      - name: Use cache
        uses: actions/cache@v2
        with:
          key: editorconfigcheckerdeps-${{inputs.checker_version}}
          restore-keys: |
            editorconfigcheckerdeps-
          path: |
            node_modules

      - name: Install editorconfig checker
        run: |
          npm install editorconfig-checker@${{inputs.checker_version}}

      - name: Check editorconfig
        run: |
          npx editorconfig-checker -exclude '\.iml$|/(node_modules|target|.idea|.git)/|^package.json$'

      - name: Check for tabs in a middle of a line
        run: |
          find . -type f \
              -not -name '*.iml' \
              -not -name '*.png' \
              -not -path '**/node_modules/**' \
              -not -path '**/target/**' \
              -not -path '**/.idea/**' \
              -not -path './.git/**' \
              -exec grep -HnE $'[^/-]\S\t+' {} \; \
            | grep . && printf '\033[0m' && exit 1 || printf '\033[0m'

